theme: osuny
_merge: deep
params:
  breadcrumb:
    position: hero-start
  posts:
    index:
      layout: grid
  summary:
    position: hero
  search:
    active: false
  logo:
    header: ''
    footer: ''